# Generated by Django 6.0.4 on 2026-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail Institucional')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
